# Create as structure containing the parameters necesary to setup the request 
# and the properties of the rasters.
#
params:
  # Parmeters of the request
  requests_file:
    path: "data/feudi_mod.xlsx"
    crs: 'EPSG:6706'
    provinces:
      CAMPANIA: ['AV','BN']
    format:
      id: int
      Regione: str
      SiglaProvincia: str
      CodComune: str
      Comune: str
      Foglio: int
      Particella: int
      Pagina: int
      Ha: int
      Aa: int
      Ca: int

  request_params:
    evalscript_path: "configs/evalscript_sentinel_1.txt"
    resolution: 10 #in meters
    slots: [["2020-01-01", "2022-04-10"]] # This will superseed the automatic splitting. Set this to None for automatic (even) splitting.
    start_date: '2018-12-01'
    end_date: '2019-02-28' 
    n_chunks: 1
    collection: "SENTINEL1_IW"
    collection_alias: "sentinel-1-grd"
    mosaicking_order: None
    other_args: None
    responses: 
      default: "TIFF"
      userdata: "JSON"
    output_directory: "samples/sentinel_1"

  authentification:
    path: 'configs/auth_sentinel.yaml'

